# Generated by Django 2.1.15 on 2020-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictest',
            name='goods_pic',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
