# Generated by Django 2.1.15 on 2020-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='goods_pic',
            field=models.ImageField(default='upming/logo.png', upload_to='article_pic/'),
        ),
    ]
