# Generated by Django 2.1.15 on 2020-02-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_post_goods_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='goods_pic',
            field=models.ImageField(default='upimg/logo.png', upload_to='article_pic/'),
        ),
    ]
